### PR TITLE
Documentation for fetching images from multiple devices (#214)

### PR DESCRIPTION
**Pull request by lwasyl**

### CODE REVIEW

**Comment by xiphirx** [comment]
Could we have the plugin set this for the shell that executes the python script? That way people don't have to think about it?

**Comment by lwasyl** [comment]
@xiphirx I modified #214 instead by making `pull_screenshots` loop over all available devices by default. I decided it makes more sense since the python scripts already query ADB for stuff, and in Gradle plugin I'd need to add this logic from scratch.

I'll update this branch with proper documentation if changes in #214 are OK, the end result then is:
 - `-s` flag is used if it's passed to the python script. If not,
 - `ANDROID_SERIAL` is used (as folks might want to set it to run tests on some subset of devices already), and if it's not set
 - `adb devices` is queried and serials of all connected devices and emulators are used to pull screenshots

**Comment by lwasyl** [comment]
@xiphirx Sorry for no ping, I've updated this PR to be in line with the merged one.

Also any way to get a release with the recent changes?

**Comment by xiphirx** [comment]
Thank you! I can put up a release soon.

**Comment by xiphirx** [comment]
0.9.0 has been released with your changes, enjoy!

**Pull request merged**
