### PR TITLE
Formatted Files for suggested Android Studio Code Style

### PR DESCRIPTION
**Pull request by sridoodla**
As per Android Code Style merged in #96

### CODE REVIEW

**Comment by tdrhq** [comment]
A little uncomfortable of this changes things so widely, but okay, it looks reasonable

**Comment by sridoodla** [comment]
I uh, didn't actually run the tests. I don't *think* anything will break which wasn't already broken, but if you haven't, it's probably a good idea. If shit breaks, I can work to fix it and we can revert this PR till then.

**Comment by tdrhq** [comment]
@sridoodla I ran them locally :)

**Comment by tdrhq** [comment]
oh wait, actually I apparently ran them wrong, I'm reverting this since it's breaking stuff

**Comment by sridoodla** [comment]
haha. Let me run them then. Let me see if I can find the issue.

**Comment by sridoodla** [comment]
@tdrhq Everything passed for me.

**Comment by tdrhq** [comment]
actually, looks like ./gradlew :plugin:test broke in 5f36c4b072af6d860c9d7d106c7a08117cd20923, not sure why I didn't catch that earlier

**Comment by sridoodla** [comment]
I don't think you needed to revert this. All my tests passed. And I didn't touch the plugin package anyway.

**Pull request merged**
